### ISSUE TITLE
Linters watch logic

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/slush-es20xx#15]
In watch mode, in case 2 or more files are piped in the same batch and the first one fails JSHint/JSCS checks, the other(s) should still be ran through linters and compilers in order to keep the incremental build state consistent.

This is a relatively rare use case and I don't want to overcomplicate the pipes logic right now until I resolve some higher priority issues here, so setting a low priority for now.

**Comment by UltCombo** [comment]
To resolve this issue, I believe the incremental build logic should be changed in this way:

- Remove JSHint/JSCS fail reporters (only keep their logging reporters), so that errors are not thrown before the files reach the transpiler pipe. This depends on jscs-dev/gulp-jscs#66

- Errors in the transpiling should not break the pipe -- this can be achieved by adding an error handler or gulp-plumber. The errors should still be logged to make the user aware of what's wrong.

I'm just not sure when the unit tests should run in case an error occurred previously. Let's examine some use cases:

**Case 1:** Transpiling fails, the result is **not** written to `dest`, mocha runs the tests using an old version of the file and gives an all ok signal. This seems extremely confusing, having an "all ok" message at the end of the pipe given that transpiling failed is just wrong. Hence I believe we should not run unit tests when transpiling a file fails.

**Case 2:** JSHint/JSCS fails, transpiling succeeds. Should the tests run in this case? JSHint/JSCS can report errors quite often, so in some cases it would be counter-productive to prevent tests from running due to linter errors. In the other hand, not running tests would be more consistent with the "abort tests when errors occur in the stream" approach applied in Case 1, and the log output would be easier to assimilate -- that is, showing only the linter error(s) instead of linter errors + unit tests results.

In all cases, the errors can be "ignored" by the user by simply editing another file without fixing the one with errors, as the incremental build will only act on files that are being edited. I believe the current approach is good enough as I can't think of a better approach given the constraints:

- The incremental build cannot "break" the process/exit with an error as it is supposed to be resilient to errors that users make during development (opposite to the build task that is run before deployment).

- The incremental build only runs on modified files, it has no record of previous incremental build results.

A quick idea I just had is to add some hacks to detect linting/transpiling errors and keep track of the file paths that caused them, so that a small reminder of "other files containing errors" could be displayed at the end of a successful incremental build. But this means having to extract file paths from gulp-6to5 error messages, detect when such files are subsequently modified and pass linting and transpiling or when they're deleted to remove them from the "currently erroring" list. There are probably more edge cases that I haven't thought of yet. This would most likely be a nice addition, but it seems to be too much effort at the moment and:

- It can be mostly worked around by simply paying attention in the log output and fixing errors as they pop up.

- Even if such error slips by, it will be caught in the next build before a deploy or when booting up the incremental build task.

I need to give it some more thought, so let's keep this part as low(er) priority for the time being and I'll open a new issue if/when I need to think more about it. Let's use this issue to discuss the other cases outlined above.

**Comment by UltCombo** [comment]
Seeing as this is a major improvement that will make slush-es20xx even more magnificent than it already is, I'll most likely work on this after implementing the new linting tool and clearing the P1 issues.

**Comment by UltCombo** [comment]
@jaydson please try out the master branch now. The feedback for erroring files is orders of magnitude better now.

Run `npm run dev` with one or more JS file containing syntax and/or linting errors and you will see what I mean. :smile_cat:

**Comment by jaydson** [comment]
Wow. Just Wow.
Works like a charm.

Congratz! 
When we will push it to Harmonic?

**Comment by UltCombo** [comment]
> When we will push it to Harmonic?

When I'm less sleepy, probably tomorrow. :stuck_out_tongue:

The hard part will be writing the `.eslintrc` file, if you can start setting one up, that would speed things up quite a bit. http://eslint.org/docs/rules/

**Comment by jaydson** [comment]
Here you go.
I tried to keep some rules of our previous style-guide (https://github.com/es6rocks/code-style).
But a lot of preferences are mine way of doing things, so feel free to review the rules and tell me what you agreed or not.

```json
{
 "env": {
        "node": true,
        "es6": true
    },
   "comma-dangle": true,
   "no-trailing-spaces": true,
   "no-cond-assign": true,
   "no-dupe-args": true,
   "no-dupe-keys": true,
   "no-duplicate-case": true,
   "no-empty": true,
   "no-extra-semi": true,
   "no-inner-declarations": true,
   "no-irregular-whitespace": true,
   "no-obj-calls": true,
   "no-reserved-keys": true,
   "no-unreachable": true,
   "valid-typeof": true,
   "block-scoped-var": true,
   "curly": true,
   "default-case": true,
   "eqeqeq": true,
   "no-else-return": true,
   "no-extend-native": true,
   "no-lone-blocks": true, 
   "no-loop-func": true,
   "no-multi-spaces": true,
   "no-multi-str": true,
   "no-native-reassign": true, 
   "no-new-func": true,
   "no-param-reassign": true,
   "no-redeclare": true,
   "no-sequences": true,
   "no-with": true,
   "yoda": true,
   "indent": 4,
   "brace-style": true,
   "camelcase": true,
   "comma-spacing": true,
   "comma-style": true,
   "eol-last": true,
   "new-cap": true,
   "new-parens": true,
   "no-mixed-spaces-and-tabs": true,
   "no-multiple-empty-lines": true,
   "no-spaced-func": true,
   "no-trailing-spaces": true,
   "quotes": "single",
   "semi": true,
   "semi-spacing": true,
   "spaced-line-comment": true
}
```

**Comment by UltCombo** [comment]
Nice!
Guess I'll not include the rules which are enabled by default to keep the rules file simpler, then run a diff with my rules file and we can decide the final rules in the PR that I'll open in the Harmonic repository.

**Comment by jaydson** [comment]
Sounds good to me :+1:
