### ISSUE TITLE
Missing slush

### ISSUE THREAD

**Issue by jaydson** [es6rocks/slush-es20xx#21]
There's a way to prevent install `slush-es20xx` if `slush` is not already installed?

**Comment by UltCombo** [comment]
We could set it as a peer dependency, but there's a lot of discussion around whether peerDeps should ever be used at all. E.g. https://github.com/npm/npm/issues/5080 https://github.com/npm/npm/issues/6565

Grunt and gulp plugins don't prevent the user from installing them without the respective framework installed, as the user can just install the framework afterwards.

**Comment by UltCombo** [comment]
I understand your line of thought though, it would good user experience to display a message. I just can't think of a proper way to do that in the npm ecosystem at the moment. Perhaps when/if peerDeps are downgraded to simply warning the user we can make use of them.

**Comment by UltCombo** [comment]
I'd personally wait until [npm@3 is released](https://github.com/npm/npm/issues/6565#issuecomment-74971689) and ships by default with Node/io.js, then add slush as a peer dependency.

But if you really want to go the extra mile and add the warning anyway, it is possible to do a `which` check (using the [`which` package](https://www.npmjs.com/package/which)) in the [install script](https://github.com/es6rocks/slush-es20xx/blob/master/install.js). The file is already a hack in itself, so I wouldn't really mind it.
@jaydson feel free to hack it if you'd like. `=]`

**Comment by jaydson** [comment]
I was just wondering.
It seems it is not a priority for the project right now.
Perhaps, if we just change the install order on the instructions (README) will help a lot, i mean, tell to install `slush` first.

**Comment by UltCombo** [comment]
Good idea! :smiley:
I'm working on the 2.0 branch right now, feel free to edit the readme in the master or 2.0 branch -- I'll merge them later.

**Comment by UltCombo** [comment]
@jaydson I've updated the install instructions: https://github.com/es6rocks/slush-es20xx#install

**Comment by jaydson** [comment]
:+1:
