### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by jaydson** [es6rocks/slush-es20xx#22]
`slush-es20xx` is throwing the following error:
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Line comments must be preceded with a blank line at index.js :
     2 |
     3 |// jscs:disable disallowSpacesInsideParentheses
     4 |console.log(`hello ${world}`);
```

This error happens both in the initial setup and running `npm run dev`.

**Comment by UltCombo** [comment]
Try installing from Git, I've already replaced JSHint/JSCS with ESLint in the master branch. You can also try the 2.0 branch for some cutting some edge experiments. `=]`

**Comment by UltCombo** [comment]
Closing as this is fixed in the master branch (JSCS is no longer used).
Please reopen if you still experience issues.

**Comment by jaydson** [comment]
:+1: Thanks

**Comment by UltCombo** [comment]
@jaydson BTW, the new logic is as follows (master branch):

- `prepublish`/`gulp build`: will throw an error/exit with a non-zero status when there is something wrong. This prevents publishing broken builds.

- `npm run dev`: reports errors but will never throw an error/break (unless there's some bug).

- Pressing Ctrl+C in watch mode now does a clean exit, that is, it waits until the current incremental build (and a possible next queued incremental build, in case you edited a file during the current incremental build before pressing Ctrl+C) finishes before exiting.

**Comment by jaydson** [comment]
Running a fresh slush version i have this error after run `slush es20xx`.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
ReferenceError: file is not defined
    at eval (lodash.templateSources[6]:9:11)
    at DestroyableTransform._transform (/home/jaydson/Workspace/slush-es20xx/node_modules/gulp-template/index.js:21:40)

```

**Comment by jaydson** [comment]
BTW, the remote branch `2.0` doesn't exists.
I think It may exists just in your machine.

**Comment by UltCombo** [comment]
@jaydson The `2.0` remote branch existed when I commented, but I've already merged it into master and deleted the `2.0` branch. :stuck_out_tongue:

As for the stream error, looks like it is a lodash template conflict with gulp-shell which uses the same syntax. Good catch!

**Comment by UltCombo** [comment]
Should be fixed now.
I'm working on some major changes to improve the incremental build feedback at the moment, I want to release a 2.0 RC soon and send a PR to Harmonic.

**Comment by jaydson** [comment]
Got it.
I'll test it soon.
Thanks.

**Comment by jaydson** [comment]
Working!

**Comment by UltCombo** [comment]
:smile: 
I'm making some optimizations in that area, which also means removing the [temporary hack](https://github.com/es6rocks/slush-es20xx/commit/f86b5d5ef8d02663ef7e82e62cd3447a11beb526) I've added to workaround this issue.

**Comment by UltCombo** [comment]
Cleaned up that part + much more: https://github.com/es6rocks/slush-es20xx/commit/d34e03bc1ca1f9c54fa62a9886a252217bddfe10

**Comment by jaydson** [comment]
:+1:
